In [1]:
!pip -q install transformers datasets accelerate scikit-learn pandas numpy matplotlib gradio huggingface_hub

In [2]:
import sys
import platform
import random

import numpy as np
import pandas as pd
import sklearn
import torch
import transformers

SEED = 42

random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)

if torch.cuda.is_available():
    torch.cuda.manual_seed_all(SEED)

print("Python version       :", sys.version)
print("Platform             :", platform.platform())
print("Pandas version       :", pd.__version__)
print("NumPy version        :", np.__version__)
print("Scikit-learn version :", sklearn.__version__)
print("Transformers version :", transformers.__version__)
print("PyTorch version      :", torch.__version__)
print("GPU available        :", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU                   :", torch.cuda.get_device_name(0))

print("Random seed          :", SEED)

Python version       : 3.13.15 (main, Aug  6 2026, 11:06:22) [GCC 13.3.0]
Platform             : Linux-6.6.122+-x86_64-with-glibc2.39
Pandas version       : 2.2.3
NumPy version        : 2.1.3
Scikit-learn version : 1.6.1
Transformers version : 5.17.0
PyTorch version      : 2.11.0+cu130
GPU available        : True
GPU                   : Tesla T4
Random seed          : 42

In [3]:
from huggingface_hub import hf_hub_download

DATA_PATH = hf_hub_download(
    repo_id="withmartian/routerbench",
    filename="routerbench_0shot.pkl",
    repo_type="dataset"
)

print("Dataset downloaded to:")
print(DATA_PATH)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

routerbench_0shot.pkl: reconstructing file:   0%|          |  0.00B / 99.6MB

routerbench_0shot.pkl: downloading bytes:           |  0.00B

Dataset downloaded to:
/root/.cache/huggingface/hub/datasets--withmartian--routerbench/snapshots/784021482c3f320c6619ed4b3bb3b41a21424fcb/routerbench_0shot.pkl

In [4]:
import pandas as pd

df = pd.read_pickle(DATA_PATH)

print("Object type:", type(df))
print("Dataset shape:", df.shape)

Object type: <class 'pandas.core.frame.DataFrame'>
Dataset shape: (36497, 37)

In [5]:
print("Columns in the dataset:\n")

for i, column in enumerate(df.columns, start=1):
    print(i, "->", column)

Columns in the dataset:

1 -> sample_id
2 -> prompt
3 -> eval_name
4 -> WizardLM/WizardLM-13B-V1.2
5 -> claude-instant-v1
6 -> claude-v1
7 -> claude-v2
8 -> gpt-3.5-turbo-1106
9 -> gpt-4-1106-preview
10 -> meta/code-llama-instruct-34b-chat
11 -> meta/llama-2-70b-chat
12 -> mistralai/mistral-7b-chat
13 -> mistralai/mixtral-8x7b-chat
14 -> zero-one-ai/Yi-34B-Chat
15 -> gpt-3.5-turbo-1106|model_response
16 -> claude-instant-v1|model_response
17 -> claude-v1|model_response
18 -> claude-v2|model_response
19 -> gpt-4-1106-preview|model_response
20 -> meta/llama-2-70b-chat|model_response
21 -> mistralai/mixtral-8x7b-chat|model_response
22 -> zero-one-ai/Yi-34B-Chat|model_response
23 -> WizardLM/WizardLM-13B-V1.2|model_response
24 -> meta/code-llama-instruct-34b-chat|model_response
25 -> mistralai/mistral-7b-chat|model_response
26 -> gpt-3.5-turbo-1106|total_cost
27 -> claude-instant-v1|total_cost
28 -> claude-v1|total_cost
29 -> claude-v2|total_cost
30 -> gpt-4-1106-preview|total_cost
31 -> meta/llama-2-70b-chat|total_cost
32 -> mistralai/mixtral-8x7b-chat|total_cost
33 -> zero-one-ai/Yi-34B-Chat|total_cost
34 -> WizardLM/WizardLM-13B-V1.2|total_cost
35 -> meta/code-llama-instruct-34b-chat|total_cost
36 -> mistralai/mistral-7b-chat|total_cost
37 -> oracle_model_to_route_to

In [6]:
display(df.head(5))

,sample_id,prompt,eval_name,WizardLM/WizardLM-13B-V1.2,claude-instant-v1,claude-v1,claude-v2,gpt-3.5-turbo-1106,gpt-4-1106-preview,meta/code-llama-instruct-34b-chat,...,claude-v1|total_cost,claude-v2|total_cost,gpt-4-1106-preview|total_cost,meta/llama-2-70b-chat|total_cost,mistralai/mixtral-8x7b-chat|total_cost,zero-one-ai/Yi-34B-Chat|total_cost,WizardLM/WizardLM-13B-V1.2|total_cost,meta/code-llama-instruct-34b-chat|total_cost,mistralai/mistral-7b-chat|total_cost,oracle_model_to_route_to
0,Chinese_character_riddles.dev.0,['猜字谜，根据我给的描述猜出一个字(请从汉字的字形、发音、意义以及字的拆分组合等角度考虑)...,Chinese_character_riddles,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.004904,0.006488,0.00973,0.000266,0.000166,0.000250,0.000103,0.000236,0.000062,no_model_correct
1,Chinese_character_riddles.dev.1,['猜字谜，根据我给的描述猜出一个字(请从汉字的字形、发音、意义以及字的拆分组合等角度考虑)...,Chinese_character_riddles,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.003096,0.004704,0.01077,0.000257,0.000227,0.000226,0.000073,0.000128,0.000050,no_model_correct
2,Chinese_character_riddles.dev.10,['猜字谜，根据我给的描述猜出一个字(请从汉字的字形、发音、意义以及字的拆分组合等角度考虑)...,Chinese_character_riddles,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.002480,0.003728,0.01105,0.000232,0.000215,0.000215,0.000138,0.000150,0.000051,zero-one-ai/Yi-34B-Chat
3,Chinese_character_riddles.dev.11,['猜字谜，根据我给的描述猜出一个字(请从汉字的字形、发音、意义以及字的拆分组合等角度考虑)...,Chinese_character_riddles,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.003088,0.004960,0.00908,0.000287,0.000117,0.000318,0.000104,0.000315,0.000045,zero-one-ai/Yi-34B-Chat
4,Chinese_character_riddles.dev.12,['猜字谜，根据我给的描述猜出一个字(请从汉字的字形、发音、意义以及字的拆分组合等角度考虑)...,Chinese_character_riddles,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.002272,0.004912,0.01322,0.000254,0.000097,0.000210,0.000112,0.000190,0.000039,no_model_correct

In [7]:
display(df.head(1).T)

                                                                                                  0
sample_id                                                           Chinese_character_riddles.dev.0
prompt                                            ['猜字谜，根据我给的描述猜出一个字(请从汉字的字形、发音、意义以及字的拆分组合等角度考虑)...
eval_name                                                                 Chinese_character_riddles
WizardLM/WizardLM-13B-V1.2                                                                      0.0
claude-instant-v1                                                                               0.0
claude-v1                                                                                       0.0
claude-v2                                                                                       0.0
gpt-3.5-turbo-1106                                                                              0.0
gpt-4-1106-preview                                                                              0.0
meta/code-llama-instruct-34b-chat                                                               0.0
meta/llama-2-70b-chat                                                                           0.0
mistralai/mistral-7b-chat                                                                       0.0
mistralai/mixtral-8x7b-chat                                                                     0.0
zero-one-ai/Yi-34B-Chat                                                                         0.0
gpt-3.5-turbo-1106|model_response                 ['这个字谜描述了一个汉字的构造和意义。根据描述，可以推测这个字包含有古代的“刚”字，后来有...
claude-instant-v1|model_response                                                            ['[笑]']
claude-v1|model_response                          ['这个字谜的描述涉及到古字的拆分和组合,豆字的插入,以及产生的意思让人笑开怀。考虑到这些因...
claude-v2|model_response                          ['好的,让我试着分析一下这个猜字谜的提示。\n\n"古字刚分开"可能指的是一个古老的字被拆...
gpt-4-1106-preview|model_response                 ['这个字谜描述了一个汉字的形成。首先，“古字刚分开”提示我们这个字可能与“古”有关，且“古...
meta/llama-2-70b-chat|model_response              [' Based on the description you provided, my f...
mistralai/mixtral-8x7b-chat|model_response        ['Based on the description, it seems like the ...
zero-one-ai/Yi-34B-Chat|model_response            ['\n推理：\n1. 古字刚分开：这个描述可能暗示着我们要找的字是由“古”字去掉一部分得到...
WizardLM/WizardLM-13B-V1.2|model_response         ['根据描述，我推测这个谜题的答案可能是“豆”。\n\n1. 汉字的字形："豆"字的形状像是...
meta/code-llama-instruct-34b-chat|model_response  [' Based on the description, I would guess tha...
mistralai/mistral-7b-chat|model_response          ['The character being guessed is "挤" (dòu).\n\...
gpt-3.5-turbo-1106|total_cost                                                              0.000527
claude-instant-v1|total_cost                                                               0.000099
claude-v1|total_cost                                                                       0.004904
claude-v2|total_cost                                                                       0.006488
gpt-4-1106-preview|total_cost                                                               0.00973
meta/llama-2-70b-chat|total_cost                                                           0.000266
mistralai/mixtral-8x7b-chat|total_cost                                                     0.000166
zero-one-ai/Yi-34B-Chat|total_cost                                                          0.00025
WizardLM/WizardLM-13B-V1.2|total_cost                                                      0.000103
meta/code-llama-instruct-34b-chat|total_cost                                               0.000236
mistralai/mistral-7b-chat|total_cost                                                       0.000062
oracle_model_to_route_to                                                           no_model_correct

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36497 entries, 0 to 36496
Data columns (total 37 columns):
 #   Column                                            Non-Null Count  Dtype
---  ------                                            --------------  -----
 0   sample_id                                         36497 non-null  object
 1   prompt                                            36497 non-null  object
 2   eval_name                                         36497 non-null  object
 3   WizardLM/WizardLM-13B-V1.2                        36497 non-null  object
 4   claude-instant-v1                                 36497 non-null  object
 5   claude-v1                                         36497 non-null  object
 6   claude-v2                                         36497 non-null  object
 7   gpt-3.5-turbo-1106                                36497 non-null  object
 8   gpt-4-1106-preview                                36497 non-null  object
 9   meta/code-llama-instruct-34b-chat                 36497 non-null  object
 10  meta/llama-2-70b-chat                             36497 non-null  object
 11  mistralai/mistral-7b-chat                         36497 non-null  object
 12  mistralai/mixtral-8x7b-chat                       36497 non-null  object
 13  zero-one-ai/Yi-34B-Chat                           36497 non-null  object
 14  gpt-3.5-turbo-1106|model_response                 36497 non-null  object
 15  claude-instant-v1|model_response                  36497 non-null  object
 16  claude-v1|model_response                          36497 non-null  object
 17  claude-v2|model_response                          36497 non-null  object
 18  gpt-4-1106-preview|model_response                 36497 non-null  object
 19  meta/llama-2-70b-chat|model_response              36497 non-null  object
 20  mistralai/mixtral-8x7b-chat|model_response        36497 non-null  object
 21  zero-one-ai/Yi-34B-Chat|model_response            36497 non-null  object
 22  WizardLM/WizardLM-13B-V1.2|model_response         36497 non-null  object
 23  meta/code-llama-instruct-34b-chat|model_response  36497 non-null  object
 24  mistralai/mistral-7b-chat|model_response          36497 non-null  object
 25  gpt-3.5-turbo-1106|total_cost                     36497 non-null  float64
 26  claude-instant-v1|total_cost                      36497 non-null  float64
 27  claude-v1|total_cost                              36497 non-null  float64
 28  claude-v2|total_cost                              36497 non-null  float64
 29  gpt-4-1106-preview|total_cost                     36497 non-null  float64
 30  meta/llama-2-70b-chat|total_cost                  36497 non-null  float64
 31  mistralai/mixtral-8x7b-chat|total_cost            36497 non-null  float64
 32  zero-one-ai/Yi-34B-Chat|total_cost                36497 non-null  float64
 33  WizardLM/WizardLM-13B-V1.2|total_cost             36497 non-null  float64
 34  meta/code-llama-instruct-34b-chat|total_cost      36497 non-null  float64
 35  mistralai/mistral-7b-chat|total_cost              36497 non-null  float64
 36  oracle_model_to_route_to                          36497 non-null  object
dtypes: float64(11), object(26)
memory usage: 10.3+ MB

In [9]:
possible_domain_columns = [
    c for c in df.columns
    if any(word in c.lower() for word in ["eval", "dataset", "task", "domain"])
]

print("Possible domain columns:")
print(possible_domain_columns)

Possible domain columns:
['eval_name']

In [10]:
for col in possible_domain_columns:
    print("\n======================")
    print("COLUMN:", col)
    print("======================")

    print(df[col].value_counts(dropna=False).head(100))

======================
COLUMN: eval_name
======================
eval_name
hellaswag                    10042
grade-school-math             7450
mmlu-professional-law         1534
arc-challenge                 1470
winogrande                    1267
                             ...
chinese_idioms                  15
chinese_poem                    15
chinese-remainder-theorem       15
chinese_chu_ci                  15
test-match                       3
Name: count, Length: 86, dtype: int64

In [11]:
possible_model_columns = [
    c for c in df.columns
    if "model" in c.lower()
]

print(possible_model_columns)

['gpt-3.5-turbo-1106|model_response', 'claude-instant-v1|model_response', 'claude-v1|model_response', 'claude-v2|model_response', 'gpt-4-1106-preview|model_response', 'meta/llama-2-70b-chat|model_response', 'mistralai/mixtral-8x7b-chat|model_response', 'zero-one-ai/Yi-34B-Chat|model_response', 'WizardLM/WizardLM-13B-V1.2|model_response', 'meta/code-llama-instruct-34b-chat|model_response', 'mistralai/mistral-7b-chat|model_response', 'oracle_model_to_route_to']

In [12]:
for col in possible_model_columns:
    if df[col].nunique() < 100:
        print("\nCOLUMN:", col)
        print(df[col].value_counts(dropna=False))

COLUMN: oracle_model_to_route_to
oracle_model_to_route_to
mistralai/mistral-7b-chat            10065
WizardLM/WizardLM-13B-V1.2            8342
mistralai/mixtral-8x7b-chat           6140
zero-one-ai/Yi-34B-Chat               5309
claude-instant-v1                     1580
no_model_correct                      1308
gpt-3.5-turbo-1106                    1069
gpt-4-1106-preview                     771
meta/llama-2-70b-chat                  666
meta/code-llama-instruct-34b-chat      477
claude-v1                              425
claude-v2                              345
Name: count, dtype: int64

In [13]:
possible_correctness_columns = [
    c for c in df.columns
    if any(word in c.lower() for word in [
        "performance",
        "correct",
        "score"
    ])
]

print(possible_correctness_columns)

[]

In [15]:
for col in possible_correctness_columns:
    print("\n======================")
    print("COLUMN:", col)
    print("======================")

    print("Data type:", df[col].dtype)
    print("Unique values:")
    print(df[col].dropna().unique()[:30])

    print("\nCounts:")
    print(df[col].value_counts(dropna=False).head(30))

In [16]:
possible_cost_columns = [
    c for c in df.columns
    if any(word in c.lower() for word in [
        "cost",
        "price"
    ])
]

print(possible_cost_columns)

['gpt-3.5-turbo-1106|total_cost', 'claude-instant-v1|total_cost', 'claude-v1|total_cost', 'claude-v2|total_cost', 'gpt-4-1106-preview|total_cost', 'meta/llama-2-70b-chat|total_cost', 'mistralai/mixtral-8x7b-chat|total_cost', 'zero-one-ai/Yi-34B-Chat|total_cost', 'WizardLM/WizardLM-13B-V1.2|total_cost', 'meta/code-llama-instruct-34b-chat|total_cost', 'mistralai/mistral-7b-chat|total_cost']

In [17]:
for col in possible_cost_columns:
    print("\nCOLUMN:", col)
    print(df[col].describe())

COLUMN: gpt-3.5-turbo-1106|total_cost
count    36497.000000
mean         0.000243
std          0.000184
min          0.000022
25%          0.000100
50%          0.000188
75%          0.000315
max          0.006443
Name: gpt-3.5-turbo-1106|total_cost, dtype: float64

COLUMN: claude-instant-v1|total_cost
count    36497.000000
mean         0.000233
std          0.000210
min          0.000018
25%          0.000081
50%          0.000152
75%          0.000275
max          0.001908
Name: claude-instant-v1|total_cost, dtype: float64

COLUMN: claude-v1|total_cost
count    36497.000000
mean         0.002145
std          0.001806
min          0.000136
25%          0.000808
50%          0.001528
75%          0.002672
max          0.029464
Name: claude-v1|total_cost, dtype: float64

COLUMN: claude-v2|total_cost
count    36497.000000
mean         0.002419
std          0.002191
min          0.000136
25%          0.000808
50%          0.001560
75%          0.003264
max          0.019560
Name: claude-v2|total_cost, dtype: float64

COLUMN: gpt-4-1106-preview|total_cost
count    36497.000000
mean         0.003293
std          0.003429
min          0.000170
25%          0.001010
50%          0.001930
75%          0.003740
max          0.050730
Name: gpt-4-1106-preview|total_cost, dtype: float64

COLUMN: meta/llama-2-70b-chat|total_cost
count    36497.000000
mean         0.000203
std          0.000133
min          0.000013
25%          0.000090
50%          0.000172
75%          0.000292
max          0.002917
Name: meta/llama-2-70b-chat|total_cost, dtype: float64

COLUMN: mistralai/mixtral-8x7b-chat|total_cost
count    36497.000000
mean         0.000135
std          0.000088
min          0.000011
25%          0.000060
50%          0.000113
75%          0.000185
max          0.001655
Name: mistralai/mixtral-8x7b-chat|total_cost, dtype: float64

COLUMN: zero-one-ai/Yi-34B-Chat|total_cost
count    36497.000000
mean         0.000186
std          0.000132
min          0.000020
25%          0.000079
50%          0.000148
75%          0.000236
max          0.001247
Name: zero-one-ai/Yi-34B-Chat|total_cost, dtype: float64

COLUMN: WizardLM/WizardLM-13B-V1.2|total_cost
count    36497.000000
mean         0.000073
std          0.000053
min          0.000008
25%          0.000030
50%          0.000056
75%          0.000095
max          0.000462
Name: WizardLM/WizardLM-13B-V1.2|total_cost, dtype: float64

COLUMN: meta/code-llama-instruct-34b-chat|total_cost
count    36497.000000
mean         0.000172
std          0.000111
min          0.000012
25%          0.000077
50%          0.000140
75%          0.000237
max          0.001062
Name: meta/code-llama-instruct-34b-chat|total_cost, dtype: float64

COLUMN: mistralai/mistral-7b-chat|total_cost
count    36497.000000
mean         0.000046
std          0.000038
min          0.000004
25%          0.000020
50%          0.000037
75%          0.000060
max          0.000828
Name: mistralai/mistral-7b-chat|total_cost, dtype: float64

In [18]:
missing = pd.DataFrame({
    "missing_count": df.isna().sum(),
    "missing_percent": (df.isna().mean() * 100).round(2)
})

display(
    missing.sort_values(
        "missing_percent",
        ascending=False
    )
)

,missing_count,missing_percent
sample_id,0,0.0
prompt,0,0.0
eval_name,0,0.0
WizardLM/WizardLM-13B-V1.2,0,0.0
claude-instant-v1,0,0.0
claude-v1,0,0.0
claude-v2,0,0.0
gpt-3.5-turbo-1106,0,0.0
gpt-4-1106-preview,0,0.0
meta/code-llama-instruct-34b-chat,0,0.0
meta/llama-2-70b-chat,0,0.0
mistralai/mistral-7b-chat,0,0.0
mistralai/mixtral-8x7b-chat,0,0.0
zero-one-ai/Yi-34B-Chat,0,0.0
gpt-3.5-turbo-1106|model_response,0,0.0
claude-instant-v1|model_response,0,0.0
claude-v1|model_response,0,0.0
claude-v2|model_response,0,0.0
gpt-4-1106-preview|model_response,0,0.0
meta/llama-2-70b-chat|model_response,0,0.0
mistralai/mixtral-8x7b-chat|model_response,0,0.0
zero-one-ai/Yi-34B-Chat|model_response,0,0.0
WizardLM/WizardLM-13B-V1.2|model_response,0,0.0
meta/code-llama-instruct-34b-chat|model_response,0,0.0
mistralai/mistral-7b-chat|model_response,0,0.0
gpt-3.5-turbo-1106|total_cost,0,0.0
claude-instant-v1|total_cost,0,0.0
claude-v1|total_cost,0,0.0
claude-v2|total_cost,0,0.0
gpt-4-1106-preview|total_cost,0,0.0
meta/llama-2-70b-chat|total_cost,0,0.0
mistralai/mixtral-8x7b-chat|total_cost,0,0.0
zero-one-ai/Yi-34B-Chat|total_cost,0,0.0
WizardLM/WizardLM-13B-V1.2|total_cost,0,0.0
meta/code-llama-instruct-34b-chat|total_cost,0,0.0
mistralai/mistral-7b-chat|total_cost,0,0.0
oracle_model_to_route_to,0,0.0

In [20]:
MODEL_COLS = [
    "WizardLM/WizardLM-13B-V1.2",
    "claude-instant-v1",
    "claude-v1",
    "claude-v2",
    "gpt-3.5-turbo-1106",
    "gpt-4-1106-preview",
    "meta/code-llama-instruct-34b-chat",
    "meta/llama-2-70b-chat",
    "mistralai/mistral-7b-chat",
    "mistralai/mixtral-8x7b-chat",
    "zero-one-ai/Yi-34B-Chat"
]

print("Number of models:", len(MODEL_COLS))

for model in MODEL_COLS:
    print(model)

Number of models: 11
WizardLM/WizardLM-13B-V1.2
claude-instant-v1
claude-v1
claude-v2
gpt-3.5-turbo-1106
gpt-4-1106-preview
meta/code-llama-instruct-34b-chat
meta/llama-2-70b-chat
mistralai/mistral-7b-chat
mistralai/mixtral-8x7b-chat
zero-one-ai/Yi-34B-Chat

In [21]:
mask_mmlu = df["eval_name"].str.startswith("mmlu-", na=False)
mask_arc = df["eval_name"].eq("arc-challenge")
mask_gsm8k = df["eval_name"].eq("grade-school-math")

project_df = df[
    mask_mmlu | mask_arc | mask_gsm8k
].copy()

print("Original dataset:", len(df))
print("Project subset:", len(project_df))

print("\nRaw task counts:")
print(project_df["eval_name"].value_counts())

Original dataset: 36497
Project subset: 22962

Raw task counts:
eval_name
grade-school-math                           7450
mmlu-professional-law                       1534
arc-challenge                               1470
mmlu-moral-scenarios                         895
mmlu-miscellaneous                           783
mmlu-professional-psychology                 612
mmlu-high-school-psychology                  545
mmlu-high-school-macroeconomics              390
mmlu-elementary-mathematics                  378
mmlu-moral-disputes                          346
mmlu-prehistory                              324
mmlu-philosophy                              311
mmlu-high-school-biology                     310
mmlu-nutrition                               306
mmlu-professional-accounting                 282
mmlu-professional-medicine                   272
mmlu-high-school-mathematics                 270
mmlu-clinical-knowledge                      265
mmlu-security-studies                        245
mmlu-high-school-microeconomics              238
mmlu-high-school-world-history               237
mmlu-conceptual-physics                      235
mmlu-marketing                               234
mmlu-human-aging                             223
mmlu-high-school-statistics                  216
mmlu-high-school-us-history                  204
mmlu-high-school-chemistry                   203
mmlu-sociology                               201
mmlu-high-school-geography                   198
mmlu-high-school-government-and-politics     193
mmlu-college-medicine                        173
mmlu-world-religions                         171
mmlu-virology                                166
mmlu-high-school-european-history            165
mmlu-logical-fallacies                       163
mmlu-astronomy                               152
mmlu-high-school-physics                     151
mmlu-electrical-engineering                  145
mmlu-college-biology                         144
mmlu-anatomy                                 135
mmlu-human-sexuality                         131
mmlu-formal-logic                            126
mmlu-international-law                       121
mmlu-econometrics                            114
mmlu-machine-learning                        112
mmlu-public-relations                        110
mmlu-jurisprudence                           108
mmlu-management                              103
mmlu-college-physics                         102
mmlu-college-computer-science                100
mmlu-college-mathematics                     100
mmlu-global-facts                            100
mmlu-high-school-computer-science            100
mmlu-computer-security                       100
mmlu-abstract-algebra                        100
mmlu-business-ethics                         100
mmlu-college-chemistry                       100
mmlu-medical-genetics                        100
mmlu-us-foreign-policy                       100
Name: count, dtype: int64

In [22]:
import numpy as np

project_df["domain"] = np.select(
    [
        project_df["eval_name"].str.startswith("mmlu-"),
        project_df["eval_name"].eq("arc-challenge"),
        project_df["eval_name"].eq("grade-school-math")
    ],
    [
        "MMLU",
        "ARC",
        "GSM8K"
    ],
    default="OTHER"
)

print("\nFinal domain counts:")
print(project_df["domain"].value_counts())

print("\nTotal:")
print(len(project_df))

Final domain counts:
domain
MMLU     14042
GSM8K     7450
ARC       1470
Name: count, dtype: int64

Total:
22962

In [23]:
for model in MODEL_COLS:
    print("\n", model)

    print(
        project_df[model]
        .value_counts(dropna=False)
        .sort_index()
    )

 WizardLM/WizardLM-13B-V1.2
WizardLM/WizardLM-13B-V1.2
0.0     8376
0.25    2942
0.5     1300
0.75    3161
1.0     7183
Name: count, dtype: int64

 claude-instant-v1
claude-instant-v1
0.0     5974
0.25    1439
0.5      746
0.75    5232
1.0     9571
Name: count, dtype: int64

 claude-v1
claude-v1
0.0      5011
0.25     1002
0.5       947
0.75     5486
1.0     10516
Name: count, dtype: int64

 claude-v2
claude-v2
0.0      5441
0.25      696
0.5      1144
0.75     5575
1.0     10106
Name: count, dtype: int64

 gpt-3.5-turbo-1106
gpt-3.5-turbo-1106
0.0      5235
0.25     1285
0.5      1684
0.75     4435
1.0     10323
Name: count, dtype: int64

 gpt-4-1106-preview
gpt-4-1106-preview
0.0      2714
0.25      314
0.5      2044
0.75     5070
1.0     12820
Name: count, dtype: int64

 meta/code-llama-instruct-34b-chat
meta/code-llama-instruct-34b-chat
0.0     14927
0.25     3874
0.5       940
0.75     2563
1.0       658
Name: count, dtype: int64

 meta/llama-2-70b-chat
meta/llama-2-70b-chat
0.0     14095
0.25     2770
0.5      1123
0.75     3506
1.0      1468
Name: count, dtype: int64

 mistralai/mistral-7b-chat
mistralai/mistral-7b-chat
0.0     11425
0.25     4650
0.5       662
0.75     2047
1.0      4178
Name: count, dtype: int64

 mistralai/mixtral-8x7b-chat
mistralai/mixtral-8x7b-chat
0.0      5423
0.25     2842
0.5      1143
0.75     3313
1.0     10241
Name: count, dtype: int64

 zero-one-ai/Yi-34B-Chat
zero-one-ai/Yi-34B-Chat
0.0      5028
0.25     2357
0.5      1239
0.75     3802
1.0     10536
Name: count, dtype: int64

In [24]:
for model in MODEL_COLS:
    values = pd.to_numeric(
        project_df[model],
        errors="coerce"
    )

    print(
        model,
        "unique =", sorted(values.dropna().unique()),
        "missing after conversion =", values.isna().sum()
    )

WizardLM/WizardLM-13B-V1.2 unique = [np.float64(0.0), np.float64(0.25), np.float64(0.5), np.float64(0.75), np.float64(1.0)] missing after conversion = 0
claude-instant-v1 unique = [np.float64(0.0), np.float64(0.25), np.float64(0.5), np.float64(0.75), np.float64(1.0)] missing after conversion = 0
claude-v1 unique = [np.float64(0.0), np.float64(0.25), np.float64(0.5), np.float64(0.75), np.float64(1.0)] missing after conversion = 0
claude-v2 unique = [np.float64(0.0), np.float64(0.25), np.float64(0.5), np.float64(0.75), np.float64(1.0)] missing after conversion = 0
gpt-3.5-turbo-1106 unique = [np.float64(0.0), np.float64(0.25), np.float64(0.5), np.float64(0.75), np.float64(1.0)] missing after conversion = 0
gpt-4-1106-preview unique = [np.float64(0.0), np.float64(0.25), np.float64(0.5), np.float64(0.75), np.float64(1.0)] missing after conversion = 0
meta/code-llama-instruct-34b-chat unique = [np.float64(0.0), np.float64(0.25), np.float64(0.5), np.float64(0.75), np.float64(1.0)] missing after conversion = 0
meta/llama-2-70b-chat unique = [np.float64(0.0), np.float64(0.25), np.float64(0.5), np.float64(0.75), np.float64(1.0)] missing after conversion = 0
mistralai/mistral-7b-chat unique = [np.float64(0.0), np.float64(0.25), np.float64(0.5), np.float64(0.75), np.float64(1.0)] missing after conversion = 0
mistralai/mixtral-8x7b-chat unique = [np.float64(0.0), np.float64(0.25), np.float64(0.5), np.float64(0.75), np.float64(1.0)] missing after conversion = 0
zero-one-ai/Yi-34B-Chat unique = [np.float64(0.0), np.float64(0.25), np.float64(0.5), np.float64(0.75), np.float64(1.0)] missing after conversion = 0

In [25]:
print(project_df["prompt"].map(type).value_counts())

prompt
<class 'str'>    22962
Name: count, dtype: int64

In [26]:
print("Example MMLU prompt:\n")
print(project_df[
    project_df["domain"] == "MMLU"
]["prompt"].iloc[0])

print("\n-----------------------------\n")

print("Example ARC prompt:\n")
print(project_df[
    project_df["domain"] == "ARC"
]["prompt"].iloc[0])

print("\n-----------------------------\n")

print("Example GSM8K prompt:\n")
print(project_df[
    project_df["domain"] == "GSM8K"
]["prompt"].iloc[0])

Example MMLU prompt:

['Please answer with the letter of the correct answer.\n\nFind the degree for the given field extension Q(sqrt(2), sqrt(3), sqrt(18)) over Q.\nA) 4\nB) 0\nC) 2\nD) 6\nPrint only a single choice  from "A" or "B" or "C" or "D" without explanation. Answer:']

-----------------------------

Example ARC prompt:

['An astronomer observes that a planet rotates faster after a meteorite impact. Which is the most likely effect of this increase in rotation?\nA) Planetary years will become longer.\nB) Planetary gravity will become stronger.\nC) Planetary days will become shorter.\nD) Planetary density will decrease.\nPrint only a single choice  from "A" or "B" or "C" or "D" without explanation.\nAnswer:']

-----------------------------

Example GSM8K prompt:

['TASK: Solve the following grade school math problem and provide a numerical answer.\nThe following are examples of grade school math problems and answers:\nQuestion: There are 15 trees in the grove. Grove workers will plant trees in the grove today. After they are done, there will be 21 trees. How many trees did the grove workers plant today? \nAnswer: 6\n\nQuestion: If there are 3 cars in the parking lot and 2 more cars arrive, how many cars are in the parking lot? \nAnswer: 5\n\nQuestion: Leah had 32 chocolates and her sister had 42. If they ate 35, how many pieces do they have left in total? \nAnswer: 39\n\nQuestion: Jason had 20 lollipops. He gave Denny some lollipops. Now Jason has 12 lollipops. How many lollipops did Jason give to Denny?\nAnswer: 8\n\nQuestion: Shawn has five toys. For Christmas, he got two toys each from his mom and dad. How many toys does he have now? \nAnswer: 9\n\n', 'Natalia sold clips to 48 of her friends in April, and then she sold half as many clips in May. How many clips did Natalia sell altogether in April and May?']

In [27]:
print(
    "Duplicate sample IDs:",
    project_df["sample_id"].duplicated().sum()
)

print(
    "Duplicate prompts:",
    project_df["prompt"].astype(str).duplicated().sum()
)

print(
    "Unique sample IDs:",
    project_df["sample_id"].nunique()
)

print(
    "Total rows:",
    len(project_df)
)

Duplicate sample IDs: 0
Duplicate prompts: 5
Unique sample IDs: 22962
Total rows: 22962

In [28]:
for domain in ["MMLU", "ARC", "GSM8K"]:
    print("\n")
    print("=" * 70)
    print("DOMAIN:", domain)
    print("=" * 70)

    domain_df = project_df[
        project_df["domain"] == domain
    ]

    for model in MODEL_COLS:
        values = pd.to_numeric(
            domain_df[model],
            errors="coerce"
        )

        print(
            model,
            "->",
            sorted(values.dropna().unique())
        )

======================================================================
DOMAIN: MMLU
======================================================================
WizardLM/WizardLM-13B-V1.2 -> [np.float64(0.0), np.float64(1.0)]
claude-instant-v1 -> [np.float64(0.0), np.float64(1.0)]
claude-v1 -> [np.float64(0.0), np.float64(1.0)]
claude-v2 -> [np.float64(0.0), np.float64(1.0)]
gpt-3.5-turbo-1106 -> [np.float64(0.0), np.float64(1.0)]
gpt-4-1106-preview -> [np.float64(0.0), np.float64(1.0)]
meta/code-llama-instruct-34b-chat -> [np.float64(0.0), np.float64(1.0)]
meta/llama-2-70b-chat -> [np.float64(0.0), np.float64(1.0)]
mistralai/mistral-7b-chat -> [np.float64(0.0), np.float64(1.0)]
mistralai/mixtral-8x7b-chat -> [np.float64(0.0), np.float64(1.0)]
zero-one-ai/Yi-34B-Chat -> [np.float64(0.0), np.float64(1.0)]


======================================================================
DOMAIN: ARC
======================================================================
WizardLM/WizardLM-13B-V1.2 -> [np.float64(0.0), np.float64(1.0)]
claude-instant-v1 -> [np.float64(0.0), np.float64(1.0)]
claude-v1 -> [np.float64(0.0), np.float64(1.0)]
claude-v2 -> [np.float64(0.0), np.float64(1.0)]
gpt-3.5-turbo-1106 -> [np.float64(0.0), np.float64(1.0)]
gpt-4-1106-preview -> [np.float64(0.0), np.float64(1.0)]
meta/code-llama-instruct-34b-chat -> [np.float64(0.0), np.float64(1.0)]
meta/llama-2-70b-chat -> [np.float64(0.0), np.float64(1.0)]
mistralai/mistral-7b-chat -> [np.float64(0.0), np.float64(1.0)]
mistralai/mixtral-8x7b-chat -> [np.float64(0.0), np.float64(1.0)]
zero-one-ai/Yi-34B-Chat -> [np.float64(0.0), np.float64(1.0)]


======================================================================
DOMAIN: GSM8K
======================================================================
WizardLM/WizardLM-13B-V1.2 -> [np.float64(0.0), np.float64(0.25), np.float64(0.5), np.float64(0.75), np.float64(1.0)]
claude-instant-v1 -> [np.float64(0.0), np.float64(0.25), np.float64(0.5), np.float64(0.75), np.float64(1.0)]
claude-v1 -> [np.float64(0.0), np.float64(0.25), np.float64(0.5), np.float64(0.75), np.float64(1.0)]
claude-v2 -> [np.float64(0.0), np.float64(0.25), np.float64(0.5), np.float64(0.75), np.float64(1.0)]
gpt-3.5-turbo-1106 -> [np.float64(0.0), np.float64(0.25), np.float64(0.5), np.float64(0.75), np.float64(1.0)]
gpt-4-1106-preview -> [np.float64(0.0), np.float64(0.25), np.float64(0.5), np.float64(0.75), np.float64(1.0)]
meta/code-llama-instruct-34b-chat -> [np.float64(0.0), np.float64(0.25), np.float64(0.5), np.float64(0.75), np.float64(1.0)]
meta/llama-2-70b-chat -> [np.float64(0.0), np.float64(0.25), np.float64(0.5), np.float64(0.75), np.float64(1.0)]
mistralai/mistral-7b-chat -> [np.float64(0.0), np.float64(0.25), np.float64(0.5), np.float64(0.75), np.float64(1.0)]
mistralai/mixtral-8x7b-chat -> [np.float64(0.0), np.float64(0.25), np.float64(0.5), np.float64(0.75), np.float64(1.0)]
zero-one-ai/Yi-34B-Chat -> [np.float64(0.0), np.float64(0.25), np.float64(0.5), np.float64(0.75), np.float64(1.0)]

In [29]:
score_df = project_df[MODEL_COLS].apply(
    pd.to_numeric,
    errors="coerce"
)

fractional_mask = (
    (score_df > 0) &
    (score_df < 1)
)

print(
    "Total model-question scores:",
    score_df.size
)

print(
    "Fractional scores:",
    fractional_mask.sum().sum()
)

print(
    "Questions containing at least one fractional score:",
    fractional_mask.any(axis=1).sum()
)

Total model-question scores: 252582
Fractional scores: 81333
Questions containing at least one fractional score: 7450

In [30]:
for domain in ["MMLU", "ARC", "GSM8K"]:

    idx = project_df["domain"] == domain

    sub_scores = score_df.loc[idx]

    fractional = (
        (sub_scores > 0) &
        (sub_scores < 1)
    )

    print("\n", domain)

    print(
        "Questions:",
        len(sub_scores)
    )

    print(
        "Questions with fractional scores:",
        fractional.any(axis=1).sum()
    )

    print(
        "Total fractional cells:",
        fractional.sum().sum()
    )

 MMLU
Questions: 14042
Questions with fractional scores: 0
Total fractional cells: 0

 ARC
Questions: 1470
Questions with fractional scores: 0
Total fractional cells: 0

 GSM8K
Questions: 7450
Questions with fractional scores: 7450
Total fractional cells: 81333

In [31]:
for domain in ["MMLU", "ARC", "GSM8K"]:

    idx = project_df["domain"] == domain

    sub_scores = score_df.loc[idx]

    fractional = (
        (sub_scores > 0) &
        (sub_scores < 1)
    )

    print("\n", domain)

    print(
        "Questions:",
        len(sub_scores)
    )

    print(
        "Questions with fractional scores:",
        fractional.any(axis=1).sum()
    )

    print(
        "Total fractional cells:",
        fractional.sum().sum()
    )

 MMLU
Questions: 14042
Questions with fractional scores: 0
Total fractional cells: 0

 ARC
Questions: 1470
Questions with fractional scores: 0
Total fractional cells: 0

 GSM8K
Questions: 7450
Questions with fractional scores: 7450
Total fractional cells: 81333

In [34]:
# Rebuild everything needed for fractional-score inspection

score_df = project_df[MODEL_COLS].apply(
    pd.to_numeric,
    errors="coerce"
)

fractional_mask = (
    (score_df > 0) &
    (score_df < 1)
)

fractional_rows = fractional_mask.any(axis=1)

print(
    "Questions containing at least one fractional score:",
    fractional_rows.sum()
)

# Inspect the first fractional example
row = project_df.loc[fractional_rows].iloc[0]

print("\nSample ID:")
print(row["sample_id"])

print("\nDomain:")
print(row["domain"])

print("\nTask:")
print(row["eval_name"])

print("\nPrompt:")
print(row["prompt"])

print("\nModel scores:")
for model in MODEL_COLS:
    print(model, "->", row[model])

print("\nOracle:")
print(row["oracle_model_to_route_to"])

Questions containing at least one fractional score: 7450

Sample ID:
grade-school-math.dev.0

Domain:
GSM8K

Task:
grade-school-math

Prompt:
['TASK: Solve the following grade school math problem and provide a numerical answer.\nThe following are examples of grade school math problems and answers:\nQuestion: There are 15 trees in the grove. Grove workers will plant trees in the grove today. After they are done, there will be 21 trees. How many trees did the grove workers plant today? \nAnswer: 6\n\nQuestion: If there are 3 cars in the parking lot and 2 more cars arrive, how many cars are in the parking lot? \nAnswer: 5\n\nQuestion: Leah had 32 chocolates and her sister had 42. If they ate 35, how many pieces do they have left in total? \nAnswer: 39\n\nQuestion: Jason had 20 lollipops. He gave Denny some lollipops. Now Jason has 12 lollipops. How many lollipops did Jason give to Denny?\nAnswer: 8\n\nQuestion: Shawn has five toys. For Christmas, he got two toys each from his mom and dad. How many toys does he have now? \nAnswer: 9\n\n', 'Natalia sold clips to 48 of her friends in April, and then she sold half as many clips in May. How many clips did Natalia sell altogether in April and May?']

Model scores:
WizardLM/WizardLM-13B-V1.2 -> 0.5
claude-instant-v1 -> 0.75
claude-v1 -> 0.75
claude-v2 -> 0.75
gpt-3.5-turbo-1106 -> 0.5
gpt-4-1106-preview -> 0.75
meta/code-llama-instruct-34b-chat -> 0.75
meta/llama-2-70b-chat -> 0.75
mistralai/mistral-7b-chat -> 0.5
mistralai/mixtral-8x7b-chat -> 0.75
zero-one-ai/Yi-34B-Chat -> 0.5

Oracle:
mistralai/mixtral-8x7b-chat

In [35]:
row = project_df.loc[fractional_rows].iloc[0]

In [36]:
fractional_rows = fractional_mask.any(axis=1)